services:
  - type: web  # ← CHANGE from worker to web
    name: ysg-telegram-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false